# Generated by Django 6.0.1 on 2026-02-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
    ]
