# Generated by Django 6.0.1 on 2026-02-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='payment_year',
            field=models.IntegerField(blank=True, default=2026, null=True),
        ),
    ]
