# Generated by Django 6.0.1 on 2026-02-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_add_old_arrears'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='old_arrears',
            field=models.FloatField(default=0),
        ),
    ]
