# Generated by Django 6.0.1 on 2026-02-17 10:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_fee_payment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='receipt_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='old_arrears',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
