# Generated by Django 6.0.1 on 2026-02-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_fee_old_arrears'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='date_paid',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='receipt',
        ),
    ]
