# Generated by Django 6.0.1 on 2026-02-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_fee_receipt_number_alter_fee_old_arrears'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='receipt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
