# Generated by Django 6.0.1 on 2026-02-10 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_remove_fee_date_paid_remove_fee_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='date_paid',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fee',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/'),
        ),
    ]
