# Generated by Django 6.0.1 on 2026-02-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_fee_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='receipt_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
