# Generated by Django 6.0.1 on 2026-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_feestructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='grade',
            field=models.CharField(help_text='Select the registered class/grade. Choices come from Student model.', max_length=50),
        ),
    ]
