# Generated by Django 6.0.1 on 2026-02-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PAYMENT_CREATE', 'Payment Created'), ('PAYMENT_UPDATE', 'Payment Updated'), ('PAYMENT_DELETE', 'Payment Deleted'), ('STUDENT_CREATE', 'Student Created'), ('STUDENT_UPDATE', 'Student Updated'), ('STUDENT_DELETE', 'Student Deleted'), ('RECEIPT_GENERATE', 'Receipt Generated')], max_length=30),
        ),
    ]
