# Generated by Django 6.0.1 on 2026-02-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
