# Generated by Django 6.0.1 on 2026-02-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_alter_activitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='fee',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.term'),
        ),
    ]
