# Generated by Django 6.0.1 on 2026-02-23 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_fee_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='grade',
            field=models.CharField(help_text='Class or grade level', max_length=50),
        ),
        migrations.AddField(
            model_name='fee',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='fees.academicyear'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year for this fee structure', on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='fees.academicyear'),
        ),
    ]
