# Generated by Django 6.0.1 on 2026-02-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_term_alter_fee_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mpesa', 'Mpesa')], max_length=10, null=True),
        ),
    ]
