# Generated by Django 6.0.1 on 2026-03-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_academicyear_feestructure_created_at_and_more'),
        ('students_app', '0005_academicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PAYMENT_CREATE', 'Payment Created'), ('PAYMENT_UPDATE', 'Payment Updated'), ('PAYMENT_DELETE', 'Payment Deleted'), ('STUDENT_CREATE', 'Student Created'), ('STUDENT_UPDATE', 'Student Updated'), ('STUDENT_DELETE', 'Student Deleted'), ('RECEIPT_GENERATE', 'Receipt Generated'), ('STUDENT_PROMOTE', 'Student Promoted'), ('STUDENT_EDITED', 'Student Edited')], max_length=30),
        ),
        migrations.CreateModel(
            name='FeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present / Billable'), ('ABSENT', 'Not Present / Exempted'), ('CLEARED', 'Cleared')], max_length=20)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.term')),
            ],
        ),
    ]
