# Generated by Django 6.0.1 on 2026-02-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('last_grade', models.CharField(max_length=20)),
                ('year_of_completion', models.IntegerField()),
            ],
        ),
    ]
