# Generated by Django 6.0.1 on 2026-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_completion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
