# Generated by Django 6.0.1 on 2026-02-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_usedadmissionnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old')], default='New', max_length=10),
        ),
    ]
