# Generated by Django 6.0.1 on 2026-02-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_student_is_alumni_student_year_of_completion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumni',
        ),
    ]
