# Generated by Django 6.0.1 on 2026-02-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0005_term_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='old_arrears',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_year',
            field=models.IntegerField(),
        ),
    ]
