# Generated by Django 6.0.1 on 2026-02-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0006_alter_fee_amount_paid_alter_fee_old_arrears_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_type',
        ),
    ]
